- src/main/resources/lib/officeBranch/update.ts
Publiserer konkrete office-id'er fremfor hele pathen. Unngår problemet når et element i en undermappe ikke er committed i XP (feks noen som jobber på redaksjonelt kontorinnhold).
Fikser feil ved sletting av kontor i XP som ikke lenger finnes i NORG.
Testet lokalt og på q6.
> Forbedrer publisering av kontorer endret etter NORG-import

- src/main/resources/lib/guillotine/queries/fragments/components/parts/partFormDetails.graphql
- src/main/resources/lib/guillotine/queries/fragments/content-types/formDetailsFragment.graphql
- src/main/resources/lib/guillotine/schema/schema-creation-callbacks/form-details.ts
- src/main/resources/site/content-types/form-details/form-details.ts
- src/main/resources/site/content-types/form-details/form-details.xml
- src/main/resources/site/parts/form-details/form-details-part-config.ts
- src/main/resources/site/parts/form-details/form-details.xml
- Åpner opp for å legge til flere kategorier samtidig (Søknad, klage/anke og ettersendelse) i samme skjemdetalj.
- Kan styre hvilke detaljer som skal vises når man setter inn en part for skjemadetaljen.
- Fjerner type (digltalt / papir) siden dette ikke er behov for når vi får mellomsteg på plass.
Testes i q6 av Janne og Terje
> Tillate flere samtidige kategorier i skjemadetaljer

- src/main/resources/lib/controllers/form-details-controller.ts
- src/main/resources/site/mixins/form-details-link/form-details-link.xml
- Tillater alle hosts, ikke bare nav.no, ettersom vi noen ganger lenker til skjemaer på andre hosts.
- Fikser eksterne url'er som ikke har http-prefix
> Fjerner restriksjon på host i validering av skjema-urler på skjemadetaljer

- src/main/resources/lib/localization/layers-migration/migration-batch-job.ts
- src/main/resources/services/migrateToLayers/migrateToLayers.ts
Skal kun brukes for fragmenter. Kommer til å mate den fra et regneark som redaktørene har fått for å fylle ut språkreferanser.
> Støtter mulighet for batch-migrering til layers av forhåndsdefinert innhold

- src/main/resources/lib/constants.ts
- src/main/resources/lib/controllers/component-preview-controller.ts
- src/main/resources/lib/controllers/frontend-proxy.ts
- src/main/resources/services/sitecontent/generate-response.ts
- src/main/resources/services/sitecontent/resolve-legacy-content-redirects.ts
- Preview for draft-branchen hentes nå fra en separat instans med ekstern.dev ingress, slik at assets fra denne kan lastes av redaktører som ikke benytter VPN. Se også https://github.com/navikt/nav-enonicxp-frontend/pull/1357
- Setter XP-origin i kode fremfor å hente fra server config
- Fikser navigering til customPaths fra previewet
> Setter en separat origin for preview fra XP-frontend

- src/main/resources/lib/officeBranch/index.ts
- Kjører fetch fra norg kun en gang i timen ved lokal kjøring (hindrer mye log spam etc 😄 )
- Logger kritisk feil for norg fetch feil først etter 10 feil (og så for hver 10. feil). Er ikke så kritisk med en liten håndfull feil på denne når den kjøres hvert minutt.
> Reduserer norg import frekvens for localhost + tweaker feil-logging

- src/main/resources/services/selectedFormDetails/selectedFormDetails.ts
- src/main/resources/site/content-types/main-article/main-article.ts
- src/main/resources/site/content-types/main-article/main-article.xml
Åpner opp for at man kan velge skjemadetaljer som skal brukes i en legacy artikkelmal, samt at tjenesten som viser aktuelle skjemadetaljer også aksepterer innholdstype main-article.
Testes i Q6
> Tillater skjemadetaljer i legacy artikkelmal

- src/main/resources/lib/guillotine/queries/fragments/richText/macrosFragment.graphql
- src/main/resources/site/macros/chatbot-link/chatbot-link-config.ts
- src/main/resources/site/macros/chatbot-link/chatbot-link.xml
Innstilling for å velge om Chatbot-macro skal vises som sekundærknapp eller lenke.
Testes i dev av Olav.
> Støtter Frida-macro som knapp i tillegg til vanlig lenke

- src/main/resources/site/content-types/forms-overview/forms-overview.ts
- src/main/resources/site/content-types/forms-overview/forms-overview.xml
- src/main/resources/site/mixins/languages-legacy/languages-legacy.xml
Må ha denne inntil videre for å lenge til gammel skjemaveiviser på engelsk i språkvelgeren
> Støtter legacy språkvelger på skjemaoversikt

- src/main/resources/lib/product-utils/productList.ts
Endret filtrering av duplikater til produktoversikter:
Sjekker bare når språk ikke er bokmål og da bare etter path (ikke sortTitle)
Vanskelig å teste skikkelig da problemet med duplikater er mest synlig i prod.
Testet lokalt og da var det to av listene på nynorsk (satser og utbetalingstider) som korrekt mistet et duplikat.
> ProductList: Gjør duplikatsjekk bare mot productDetailsPath

- src/main/resources/lib/guillotine/queries/fragments/content-types/pressLandingPageFragment.graphql
- src/main/resources/lib/guillotine/schema/schema-creation-callbacks.ts
- src/main/resources/lib/guillotine/schema/schema-creation-callbacks/press-landing-page-data.ts
- src/main/resources/site/processors/page-template-processor.ts
- Sorterer nyhetsliste på presseside etter siste publiseringsdato
- Pruner listene på presseside
> Pruner og sorterer lister for nyheter på presse landingsside

- src/main/resources/lib/guillotine/schema/schema-creation-callbacks/forms-overview-data-callback.ts
Hvis externalProductUrl er satt til nav.no origin, vil url'en ikke inkluderes, og dermed vil lenken til "Mer om" ikke vises i frontend. Litt skitten løsning, men... Dette er en veldig sær edge-case for tilfeller med skjemaer som ikke har noen relevant tilknyttet side på nav.no. Muligens kun ett enkelt tifelle, så gjør det sånn inntil videre fremfor å innføre et nytt valg på produktside-typene for å skjule denne lenken.
> Workaround for å skjule lenke til produktside i skjemaoversikt

- config/dev/com.enonic.xp.web.vhost.cfg
- config/q6/com.enonic.xp.web.vhost.cfg
- src/main/resources/lib/constants.ts
SSL cert for www.dev.nav.no er utløpt, så det domenet funker ikke så bra akkurat nå. Tror vi uansett kan klare oss med kun portal-admin-* domenene for dev, så endrer begge test-miljøene til å benytte disse for eksterne tjenester.
> Endrer dev origins til portal-admin-*.oera.no

- src/main/resources/site/content-types/content-page-with-sidemenus/content-page-with-sidemenus.ts
- src/main/resources/site/content-types/current-topic-page/current-topic-page.ts
- src/main/resources/site/content-types/guide-page/guide-page.ts
- src/main/resources/site/content-types/situation-page/situation-page.ts
- src/main/resources/site/content-types/themed-article-page/themed-article-page.ts
- src/main/resources/site/content-types/tools-page/tools-page.ts
- src/main/resources/site/parts/office-editorial-detail/office-editorial-detail.xml
Kontordetaljer skal kun brukes på redaksjonell kontorside og ikke på andre sider. Da vil siden krasje. Denne PR'en legger på en begrensning på hvilke innholdstyper parten kan brukes på.
Tar også inn endel autogenererte typer som ikke har blitt committet tidligere i forbindelse med en eller annen endring.
Testes i q6
> Begrenser bruk av kontordetalj-part

- src/main/resources/lib/cache/cache-invalidate.ts
- src/main/resources/lib/cache/find-references.ts
- src/main/resources/site/layouts/situation-flex-cols/situation-flex-cols-config.ts
- Erstatter diverse spesialiserte søk for edge-cases med et generelt fulltext-query i alle felter. Dette skal fange opp alle "ikke-referanse-referanser" satt via custom-selectors, macroer osv.
- Søker alltid i alle layers for å sikre at endringer som påvirker innhold på tvers av layers alltid trigger invalidering. Må undersøke litt performance på dette og kanskje optimalisere litt (f.eks. modifisere queryene for å kunne treffe lokalisert innhold). Tar det før vi aktiverer layers i prod.
> Forbedrer referanse-søk

- package-lock.json
- package.json
- src/main/resources/lib/contentUpdate/content-update-listener.ts
Verdiene fra `no.nav.navno:payout-dates`, `no.nav.navno:global-value-set` og `no.nav.navno:global-case-time-set` skal alltid være identiske på tvers av språkversjoner. Sørger derfor for at disse ikke kan lokaliseres til layers.
> Sørger for at visse content types aldri lokaliseres til layers

- src/main/resources/lib/paths/custom-paths/custom-path.test.ts
- src/main/resources/lib/reindex-fragments.ts
- src/main/resources/lib/search/search-event-handlers.ts
- src/main/resources/main.ts
- src/main/resources/types/xp-libs/content.d.ts
- src/main/resources/webapp/webapp.ts
XP hadde en bug med indeksering av component-data i fragmenter. Denne ble fikset sånn ca april 2023, men hadde ikke tilbakevirkende effekt, dvs fragmenter som ikke har blitt endret siden fiksen mangler fortsatt felter i index-configen.
Legger til en jobb som må kjøres en gang for å oppdatere indexen på alle fragmenter. Er viktig at indexen er korrekt slik at referanse-søket fungerer ved layers-migreringen.
> Jobb for å reindeksere html-fragmenter

- src/main/resources/lib/localization/publish-events.ts
- src/main/resources/main.ts
Når content modifiseres og pushes til master programmatisk, vil push-events som brukes for å synce root-content til layers i noen tilfeller trigges før innholdet faktisk har blitt oppdatert i layerne. Dette kan skje ettersom den interne jobben i XP som syncer innholdet kjøres som en asynkron task.
Gjør derfor en ytterligere sjekk ved update-events, som sjekker timestamps på layer content vs root content for å avgjøre om en push er nødvendig for å holde de i sync.
> Fikser race-condition bug ved sync av master content til layers

- src/main/resources/lib/context/run-in-context.ts
- src/main/resources/lib/localization/locale-context.ts
- src/main/resources/services/globalValues/globalValues.ts
Kjører request-handlere for global-value services i context av kallende bruker istedenfor systembruker, ettersom brukers tilganger skal bestemme hvilke handlinger som kan utføres.
> Kjører global-value req handlers som kallende bruker

- src/main/resources/site/content-types/front-page-nested/front-page-nested.ts
- src/main/resources/site/parts/frontpage-shortcuts/frontpage-shortcuts.xml
Fjerner antallsbegrensninger for "Seksjon for snarveier". Denne brukes kun på forsider og styres av vår egen redaksjon, så jeg har avklart med Janne at det er OK å fjerne begrensningen.
Testes i dev / q6
> Fjerner antallsbegrensninger for seksjon for snarveier

- src/main/resources/services/sitecontent/resolve-redirects.ts
Sørger for at redirects går til riktig layer
> Setter locale-context ved kjøring av redirect-queries

- src/main/resources/lib/paths/editor-path.ts
Benyttes for å lenke til innhold fra custom selectors i content studio
> Bruker alltid context-relevant path for editor paths

- src/main/resources/lib/sitemap/sitemap.ts
- src/main/resources/lib/utils/array-utils.ts
- src/main/resources/main.ts
Største forbedringen her kommer fra omskrivning av måten språkversjoner resolves på. Bruker nå eksisterende data fra det initielle queryet for å resolve språkversjons-referanser, fremfor å gjøre nye queries for hvert enkelt innhold.
Reduserer tiden det tar å generere sitemappet til ca. 1/5 av tidligere (1500 sec -> 300 sec i dev).
> Optimaliserer sitemap-generering

- src/main/resources/lib/controllers/form-intermediate-step-controller.ts
- src/main/resources/lib/localization/layers-repo-utils/query-all-layers.ts
- src/main/resources/lib/paths/custom-paths/custom-path-special-types.ts
Mellomsteg vil i mange tilfeller få en initiell kort-url basert på placeholder-navnet til nyopprettet content, eks /start/unnamed-<uuid>. Fikser det slik at kort-url ikke genereres automatisk før content'et er valid. Tar dessuten å fikser opp de eksisterende unnamed-path'ene når mellomstegene åpnes i CS.
Annen endring: Ekskluderer innhold fra arkivet med multirepo layer queries
> Fikser bug med kort-url for mellomsteg

- build.gradle
- src/main/resources/lib/cache/cache-invalidate.ts
- src/main/resources/lib/cluster-utils/cluster-api.ts
- src/main/resources/lib/cluster-utils/main-datanode.ts
- src/main/resources/lib/cluster-utils/run-on-datanode.ts
- src/main/resources/lib/contentUpdate/content-update-listener.ts
- src/main/resources/lib/contentlists/remove-unpublished.ts
- src/main/resources/lib/controllers/site-info-controller.ts
- src/main/resources/lib/localization/layers-repo-utils/layers-repo-connection.ts
- src/main/resources/lib/localization/layers-repo-utils/query-all-layers.ts
- src/main/resources/lib/localization/publish-events.ts
- src/main/resources/lib/paths/custom-paths/custom-path-event-listeners.ts
- src/main/resources/lib/scheduling/scheduled-publish-updater.ts
- src/main/resources/lib/search/config.ts
- src/main/resources/lib/search/external/config.ts
- src/main/resources/lib/search/external/event-handlers.ts
- src/main/resources/lib/search/search-event-handlers.ts
- src/main/resources/lib/sitemap/sitemap.ts
- src/main/resources/main.ts
- src/main/resources/services/sitemap/sitemap.ts
- src/main/resources/tasks/refresh-main-datanode/refresh-main-datanode.ts
- src/main/resources/tasks/refresh-main-datanode/refresh-main-datanode.xml
- src/main/resources/types/xp-libs/grid.d.ts
- src/main/resources/webapp/webapp.ts
Vi kjører i dag en del jobber kun på master noden, dersom jobben kun skal kjøres en gang, fremfor på alle nodene. Dette skaper visse problemer, se linked issue https://github.com/navikt/nav-enonicxp/issues/1941
Setter derfor opp en mekanisme som velger ut en enkelt **data** node som slike jobber kan kjøres på, basert på SharedMap data i clusteret. For jobber som utfører operasjoner på Elastic-databasen erstattes dagens `isMaster`-sjekker med en sjekk på `isMainDatanode`, slik at disse jobbene alltid kjøres på en data node.
> Kjører visse jobber på en enkelt data node

- src/main/resources/lib/forms-overview/form-details-list-builder.ts
Sørger for at det ikke brukes norsk sortTitle dersom denne ikke er satt i locale fallback data.
> Setter alltid sortTitle på locale fallback data

- src/main/resources/lib/officeBranch/update.ts
- src/main/resources/services/officeBranchLanguageMigration/officeBranchLanguageMigration.ts
Language for office-branch settes til 'nb' for norsk bokmål ved import fra NORG, men det ser ut til at vi bruker kombinasjonen no og nn for henholdsvis norsk bokmål og nynorsk?
Jeg sletter tjenesten igjen så snart kontor-språk er migrert.
Testet i både dev og q6
> Midlertidig service for å sette igang migrering av language for office-branch

- src/main/resources/lib/reference-search/references-finder.ts
- Kun sider med relevante produktdetaljer skal vises som å ha en avhengighet fra oversiktssider
- Kun sider med skjemadetaljer skal vises som å ha avhengigheter fra skjemaoversikter
- Tar høyde for underkategorier for samarbeidspartner ved referansesøk for skjemaoversikter
> Gjør referanse-søk mer presist for oversiktssider

- src/main/resources/lib/paths/custom-paths/custom-path-utils.ts
- src/main/resources/services/contentSelector/contentSelector.ts
- src/main/resources/services/customPathSelector/customPathSelector.ts
- src/main/resources/services/globalValues/selector/selector.ts
- src/main/resources/services/htmlFragmentSelector/htmlFragmentSelector.ts
- src/main/resources/services/productDetailsSelector/productDetailsSelector.ts
- src/main/resources/services/service-utils.ts
- src/main/resources/site/content-types/calculator/calculator.xml
- src/main/resources/site/content-types/forms-overview/forms-overview.xml
- src/main/resources/site/macros/global-value-with-math/global-value-with-math.xml
- src/main/resources/site/macros/html-fragment/html-fragment.xml
- Fikser parsing av ids-parameteret i customselectors. Dette var tidligere et array, nå er det visst bare en komma-separert string-liste.
- Fikser bug som gjorde at saksbehandlingstider kunne velges for utregninger med globale variabler
- Fjerner språkrestriksjon på valg av ekskludert innhold på skjemaoversikter, slik at ikke-lokaliserte sider også kan ekskluderes
- Fjerner parameteret `withDescription` fra htmlFragmentSelector, ettersom denne alltid er true
> Bugfixes for CustomSelectors

- src/main/resources/lib/cache/find-paths-to-invalidate.ts
- src/main/resources/lib/constants.ts
- src/main/resources/lib/paths/path-utils.ts
- src/main/resources/services/sitecontent/public/public-response.ts
- src/main/resources/services/sitecontent/public/special-redirects.ts
- src/main/resources/services/sitecontentPaths/sitecontentPaths.ts
- Sørger for at redirects fungerer for url'er som overlapper med innhold flagget som previewOnly
- Sørger for at cache for riktige paths i frontend invalideres når en redirect i /redirects-mappa endres
> Bugfixes for redirect-responser til frontend

- src/main/resources/site/parts/breaking-news/breaking-news.ts
- src/main/resources/site/parts/breaking-news/breaking-news.xml
- src/main/resources/site/parts/link-lists/link-lists.ts
- src/main/resources/site/parts/link-lists/link-lists.xml
- src/main/resources/site/parts/link-panels/link-panels.ts
- src/main/resources/site/parts/link-panels/link-panels.xml
- src/main/resources/site/parts/main-article-linked-list/main-article-linked-list.ts
- src/main/resources/site/parts/main-article-linked-list/main-article-linked-list.xml
- src/main/resources/site/parts/main-article/main-article.ts
- src/main/resources/site/parts/main-article/main-article.xml
- src/main/resources/site/parts/main-panels/main-panels.ts
- src/main/resources/site/parts/main-panels/main-panels.xml
- src/main/resources/site/parts/menu-list/menu-list.ts
- src/main/resources/site/parts/menu-list/menu-list.xml
- src/main/resources/site/parts/notifications/notifications.ts
- src/main/resources/site/parts/notifications/notifications.xml
- src/main/resources/site/parts/office-information/office-information.ts
- src/main/resources/site/parts/office-information/office-information.xml
- src/main/resources/site/parts/page-crumbs/page-crumbs.ts
- src/main/resources/site/parts/page-crumbs/page-crumbs.xml
- src/main/resources/site/parts/page-heading/page-heading.ts
- src/main/resources/site/parts/page-heading/page-heading.xml
- src/main/resources/site/parts/page-list/page-list.ts
- src/main/resources/site/parts/page-list/page-list.xml
- src/main/resources/site/parts/publishing-calendar/publishing-calendar.ts
- src/main/resources/site/parts/publishing-calendar/publishing-calendar.xml
Parts som benyttes i legacy templates ble slettet (ved en feiltagelse?) for lenge siden. I nyeste Content Studio vises det en del feilmeldinger dersom en komponent ikke faktisk har en schema-definisjon, tar derfor og gjeninnfører disse.
> Reimplementerer gamle parts

- src/main/resources/lib/paths/custom-paths/custom-path.test.ts
- src/main/resources/site/content-types/area-page/area-page.ts
- src/main/resources/site/content-types/content-page-with-sidemenus/content-page-with-sidemenus.ts
- src/main/resources/site/content-types/current-topic-page/current-topic-page.ts
- src/main/resources/site/content-types/dynamic-page/dynamic-page.ts
- src/main/resources/site/content-types/front-page-nested/front-page-nested.ts
- src/main/resources/site/content-types/front-page/front-page.ts
- src/main/resources/site/content-types/generic-page/generic-page.ts
- src/main/resources/site/content-types/guide-page/guide-page.ts
- src/main/resources/site/content-types/main-article/main-article.ts
- src/main/resources/site/content-types/office-editorial-page/office-editorial-page.ts
- src/main/resources/site/content-types/overview/overview.ts
- src/main/resources/site/content-types/page-list/page-list.ts
- src/main/resources/site/content-types/publishing-calendar/publishing-calendar.ts
- src/main/resources/site/content-types/section-page/section-page.ts
- src/main/resources/site/content-types/situation-page/situation-page.ts
- src/main/resources/site/content-types/themed-article-page/themed-article-page.ts
- src/main/resources/site/content-types/transport-page/transport-page.ts
- src/main/resources/site/mixins/dynamic-page-common/dynamic-page-common.ts
- src/main/resources/site/mixins/seo/seo.ts
- src/main/resources/site/mixins/seo/seo.xml
Enkelte ganger ønsker vi at Google ikke forsøker å hente ut snippets fra et innhold basert på hva brukeren har søkt etter. Feks kan det gi feilaktige svar til brukeren dersom teksten vises ute av kontekst i Google-søk.
Denne funksjonen lar redaktøren sette nosnippet for hele innholdet.
Testet i q6
> Gir redaktørene mulighet til å angi nosnippet

- src/main/resources/lib/paths/path-utils.ts
- src/main/resources/lib/utils/version-utils.ts
- src/main/resources/services/service-utils.ts
- src/main/resources/services/sitecontent/public/not-found-redirects.ts
- src/main/resources/services/sitecontent/sitecontent.ts
- Validerer at id-parameteret til sitecontent-service'en er formet som en gyldig content referanse
- Setter en maks-grense for lengde på parent path-segmenter som inkluderes ved søk etter ancestor redirects
- Optimaliserer søk etter ancestor redirects: Kjører nå ett enkelt query for potensielle redirects, fremfor rekursiv sjekk på alle ancestors.
> Optimaliserer redirects-søk ved not found + bedre sitecontent params validering

- src/main/resources/lib/utils/datetime-utils.ts
- src/main/resources/lib/utils/string-utils.ts
- src/main/resources/services/contentSelector/contentSelector.ts
- src/main/resources/site/content-types/content-data-locale-fallback/content-data-locale-fallback.xml
- src/main/resources/site/content-types/forms-overview/forms-overview.xml
- src/main/resources/site/content-types/overview/overview.xml
- Fikser selector for excluded content slik at den setter audience på korrekt måte i queryet
- Fikser contentSelector service slik at den håndterer linebreaks i input-parametre
- Legger til støtte for injecting av arrays i contentSelector
- Fjerner noe ubrukt kode
> Fikser selector for excluded content for oversiktssider

- src/main/resources/lib/localization/locale-utils.ts
- src/main/resources/lib/paths/locale-paths.ts
- src/main/resources/lib/paths/public-path.ts
- src/main/resources/services/customPathSelector/customPathSelector.ts
- src/main/resources/services/sitecontent/common/find-target-content-and-locale.ts
- src/main/resources/services/sitecontent/public/special-redirects.ts
- src/main/resources/services/sitecontentPaths/sitecontentPaths.ts
Den spesifikke case'en som gjør at denne endringen er nødvendig nå, er ny engelsk forside som vi vil ha på `nav.no/en`. `/en` brukes også som en mappe for alt av "legacy" engelsk-innhold som ikke ligger i layers, derfor må vi ha mulighet for at kort-url'er/locale url'er for layers kan prioriteres over interne paths.
Vi har ingen andre interne paths som slutter på `/en|/nn/se` pdd, så denne endringen skal ikke påvirke noe eksisterende innhold.
- Tillater å sette en kort-url/customPath som overlapper med en intern _path
- Kort-url'er skal nå prioriteres over interne _path's ved resolving av requests fra frontend, dersom disse overlapper
- Paths med en gyldig locale-suffix (f.eks `/en`) skal nå alltid forsøkes å resolves til det aktuelle layeret, selv om det finnes en tilsvarende eksakt path …
> Skriver om resolving av request paths til frontend for å prioritere kort-url'er og locale-url'er

- src/main/resources/lib/search/external/document-builder/field-resolvers/audience.ts
- src/main/resources/lib/search/external/document-builder/field-resolvers/metatags.ts
- Ekskluderer `nav-og-samfunn/samarbeid`-mappa fra `nav-og-samfunn` tag.
- Setter ikke audience-felt på sider med `/presse/` url-segment
> Tweaker metatags for eksternt søk

- src/main/resources/lib/search/external/document-builder/field-resolvers/audience.ts
- src/main/resources/lib/search/external/document-builder/field-resolvers/metatags.ts
- src/main/resources/site/mixins/languages-legacy/languages-legacy.xml
- Fjerner `nav-og-samfunn`
- Fjerner analyse-nyheter fra `presse`
- Inkluderer undermålgrupper i audience-arrayet
> Tweaker metatags/audience tags for nytt søk

- src/main/resources/site/parts/dynamic-link-list/dynamic-link-list-part-config.ts
- src/main/resources/site/parts/dynamic-link-list/dynamic-link-list.xml
Lenkeliste må ha tre type visninger: vanlig, chevron og punktliste (ny). Denne PR'en fjerner "Lenker med chevron" og lar redaktøren velge samme visning via en dropdown.
Det er 3-4 sider som faktisk har Lenkeliste hvor Lenker med chevron er slått på, så vi kan gå inn i etterkant av deploy og korrigere dette slik at disse sidene fortsatt viser lenkeliste med chevron.
Testes i dev.
> Lenkeliste: Støtte visning som punktliste

- src/main/resources/lib/cache/invalidate-special-content-types.ts
- src/main/resources/lib/controllers/site-info-controller.ts
- src/main/resources/lib/scheduling/scheduled-publish-updater.ts
- src/main/resources/lib/scheduling/scheduled-publish.ts
- src/main/resources/tasks/prepublish-cache-wipe/prepublish-cache-wipe.ts
Bruker nå også repoId i key'en for jobbene, slik at invalidering i hvert repo får unik key
> Fikser bugs ved scheduled invalidering av samme contentId i flere layers

- src/main/resources/admin/widgets/dashboard-content/utils/auditLogQuery.ts
- src/main/resources/lib/utils/array-utils.ts
Fikser bugs som kan oppstå dersom `getAuditLogEntries` kun fir ett enkelt treff, og derfor ikke returnerer et array.
> Returnerer alltid et array fra auditlog query

- .xp-codegen/site/content-types/content-page-with-sidemenus/index.d.ts
- .xp-codegen/site/content-types/guide-page/index.d.ts
- .xp-codegen/site/content-types/themed-article-page/index.d.ts
- .xp-codegen/site/mixins/alternative-audience/index.d.ts
- src/main/resources/lib/guillotine/queries/fragments/content-types/contentPageWithSidemenusFragment.graphql
- src/main/resources/lib/guillotine/queries/fragments/content-types/guidePageFragment.graphql
- src/main/resources/lib/guillotine/queries/fragments/content-types/themedArticlePageFragment.graphql
- src/main/resources/lib/guillotine/schema/schema-creation-callbacks/common/audience-mixin.ts
- src/main/resources/site/mixins/alternative-audience/alternative-audience.xml
Man må kunne sette en egen label/navn hvis man har valgt "andre samarbeidspartnere" som aktuell målgruppe.
Denne PR'en gjør at frontend håndterer både string og objekt for valgt samarbeidspartner.
Testet i q6
> Aktuelle målgrupper: Kunne sette egen label for aandre samarbeidspartnere

- .xp-codegen/site/layouts/situation-flex-cols/index.d.ts
- src/main/resources/site/layouts/situation-flex-cols/situation-flex-cols.xml
Intensjonen med innstillingen var å kunne angi at en flex-col er en varehylle og hvilken type varehylle den er. Jeg har søkt igjennom og gjort en query etter sider hvor denne funksjonen er brukt, og finner ingen. Har også bekreftet med Tuva at den kan fjernes.
Testes i dev
> Fjerner innstillinger for varehylle i flex-cols

- src/main/resources/services/sitecontent/draft/draft-response.ts
- src/main/resources/services/sitecontent/public/public-response.ts
Nedskalerer også cache'en for public response, som er minimalt nyttig og er unødvendig stor.
> Cacher sitecontent response for draft

- config/dev/no.nav.navno.cfg
- config/localhost/no.nav.navno.cfg
- config/p/no.nav.navno.cfg
- config/q6/no.nav.navno.cfg
- src/main/resources/lib/constants.ts
- src/main/resources/lib/office-pages/_legacy-office-information/legacy-office-update.ts
- src/main/resources/types/global.d.ts
Dette feltet kan inneholde data kun ment for intern bruk, og bør ikke risikere å eksponeres til publikum.
Legger også inn norg2 legacy api url i appen, fremfor å sette den i config-fil på serverne.
> Fjerner enhet.sosialeTjenester feltet fra legacy kontor-sider

- src/main/resources/lib/scheduling/schedule-cleanup.ts
- src/main/resources/tasks/unpublish-expired-content/unpublish-expired-content.ts
Kom til skade for å bruke content api'et for å hente ut expired content for scheduled avpublisering ved en refactoring for en liten stund siden. Dette kan ikke (by design) hente ut innhold som er expired, må derfor bruke node api'et her. 😅 
Tar også å beholder expired scheduler-jobber en måned tilbake i tid, for å gjøre det enklere å feilsøke hvis noe scheduler-relatert feiler.
> Fikser bug som hindret automatisk avpublisering av expired content

- src/main/resources/lib/guillotine/queries/fragments/richText/macrosFragment.graphql
Pga sirkulær nøsting måtte vi skrive en litt hacky query for å få resolvet processed_html inne i en macro inne i et fragment. Denne queryen støttet ikke dersom det lå en skjemadetalj inne i html-innholdet.
Begrensningen i denne fiksen er da at skjemadetaljen ikke kan inneholde nok en fragment med html-innhold. Andre makroer slik som global verdi skal derimot støttes.
Testes i dev
> Legger til støtte for skjemadetaljer i et fragment i en processed_html

- src/main/resources/lib/search/document-builder/document-builder.ts
- src/main/resources/lib/utils/content-utils.ts
Det så ut til at innhold som er forhåndspublisert fortsatt vises i søk. Her er forslag til løsning som sjekker på at innhold ikke er prePublished før det slipper igjennom til søkeresultat.
Mulig den ekstra gangen innom isContentPrepublished er litt redundant, men jeg tenkte det best å følge eksisterende arkitektur for filtrering av ugyldig innhold på samme måte som sjekk av preview etc.
Testet i dev. Greier ikke lenger å gjenskape feilen.
> Sjekker om innhold er prepublisert før det bygges som søkedokument

- src/main/resources/lib/overview-pages/overview/transform-to-overview-item.ts
Fikser bug som gjorde at produktdetaljer ble vist på bokmål dersom produktsiden ikke var oversatt til aktuelt språk.
> Bruker locale fra produktdetaljer for å generere public paths til oversiktssider

- .xp-codegen/site/parts/frontpage-current-topics/index.d.ts
- src/main/resources/site/parts/frontpage-current-topics/frontpage-current-topics.xml
Det er behov for å kunne legge inn aktuelle saker på underforside (samarbeidspartner) uten å legge lenke til "Flere saker". Derfor må denne løftes ut av mixin og gjøres optional.
Testet i dev
> Legger inn link som egen field-set for å fjerne påkrevetregel

- src/main/resources/lib/guillotine/queries/run-sitecontent-query.ts
En feil gjorde at kontorsider for hjelpemiddelsentral forsøker å resolve office-editorial-innhold på samme måte som for lokalkontorsider. Det gjorde at fragmenter feilet. Innholdet var fortsatt synlig frontend pga Redis, så det var ingenting som traff brukere.
Testet i dev
> Fikser feil med hjelpemiddelsentral

- src/main/resources/lib/office-pages/_legacy-office-information/legacy-office-update.ts
Enkelte hjelpemiddelsentralsider må fortsatt eksistere som legacy-versjon. Setter opp en unntaksliste slik at kun disse blir importert. De er på vei over i nye maler, så vi må bare fjerne de fortløpende når vi får beskjed fra HMS.
Testet i Q6
> Re importerer enkelte hms

- src/main/resources/lib/office-pages/_legacy-office-information/legacy-office-update.ts
Fjerner import av følgende gamle hjelpemiddelsentralsider:
- Rogaland
- Møre og Romsdal
- Vest-Viken
- Øst-Viken
- Troms og FInnmark
Testes i dev
> Stopper import av flere av hjelpemiddelsentralkontorsider

- src/main/resources/lib/office-pages/_legacy-office-information/legacy-office-update.ts
Fjerner Nordland fra hjelpemiddelsentral legacy import.
Testes i dev
> Fjerner Nordland fra import av gamle hjelpemiddelsentraler

- src/main/resources/lib/controllers/form-intermediate-step-controller.ts
- src/main/resources/lib/paths/custom-paths/custom-path-content-validators.ts
- src/main/resources/services/customPathSelector/customPathSelector.ts
- src/main/resources/site/content-types/form-intermediate-step/form-intermediate-step.xml
Sider med målgruppe arbeidsgiver må starte med /arbeidsgiver
Sider med målgruppe samarbeidspartner må starte med /samarbeidspartner
> Validerer målgruppe-segment i kort-url'er

- src/main/resources/services/sitecontentPaths/sitecontentPaths.ts
Setter opp unntak for hvilke paths som skal rendres statisk.
/admin har blitt satt opp som en faktisk mappe for redaktørene og gjøre at statisk bygg feiler fordi den returnerer 404. Tidligere har admin vært en redirect som har returnert 307 og dermed ikke har feilet i statisk bygg.
Testet i dev
> Unntak fra static paths

- src/main/resources/lib/sitemap/sitemap.ts
Fjerner Kapittel-innholdstype fra sitemap dersom main-article (parent) har blitt gjort om til feks redirect.
Testes i dev
> Sitemap stop listing disabled chapters

- src/main/resources/lib/contentlists/remove-unpublished.ts
Hindrer at referanseinnhold blir pushet dersom de er markert som klar.
Testet i dev
> Ikke resolve referanser ved contentlist push

- .xp-codegen/site/layouts/product-flex-cols/index.d.ts
- .xp-codegen/site/mixins/header-with-anchor/index.d.ts
- src/main/resources/site/parts/filters-menu/filters-menu.xml
Denne fiksen påvirker bare mulighet for å sette inn en ny part for Filtreringsmeny. Versjonshistorikk og visning av sider da de tidligere hadde filtreringsmeny vil fungere som før. Det samme gjelder dersom man reverter en side til en tidligere versjon hvor Filtreringsmeny fantes.
Testes i dev
> Slår av mulighet for å sette inn Filtreringsmeny

- src/main/resources/services/sitecontentPaths/sitecontentPaths.ts
Ved sending av "test"-flagg inkluder områdesider og oversatte forsider (dvs ikke bare "/")
Testet i dev
> Endrer innholds-typer for siteContentPaths ved flagg 'test'

- src/main/resources/lib/office-pages/types.ts
- src/main/resources/lib/search/document-builder/document-builder.ts
- src/main/resources/lib/search/document-builder/field-resolvers/ingress.ts
Enkelte kontorer har stedsnavn (stort sett kommunenavn) som ikke er de samme som poststedet hvor kontoret ligger. Derfor vises for eksempel ikke Nav Midt-Buskerud når man søker på "Sigdal" som er publikumsmottaket i Sigdal kommune.
Denne fiksen prioriterer `stedsbeskrivelse` dersom et Nav-kontor har flere publikumsmottak OG stedsbeskrivelse finnes. Det er det samme feltet som bruker i fanene for å velge publikumsmottak.
Testes i dev
> Forbedre visning og søkbarhet av kontorsteder

- src/main/resources/lib/archiving/archive-old-news.ts
- src/main/resources/lib/archiving/batch-archiving.ts
- src/main/resources/main.ts
- Starter fast arkivering hver mandag kl 05:00 (vinter) og 06:00 (sommer)
- Tar hensyn til om elementet ble publisert (eller republisert) mindre enn 1 år siden.
Testes I dev i et par ukers tid av Janne og Kristin. Prod-blocken fjernes 28. april.
> Starter fast arkiveringschedule (test foreløpig i dev)

- src/main/resources/lib/external-archive/content-tree-archive.ts
- src/main/resources/services/dataQuery/utils/queryBuilder.ts
-   Endrer filter i søk og innholdstre i layers for å fikse de med migrert data
Eks: Har testet selv i dev
> Fiks slik at vi ikke viser migrerte versjoner i default, men i layers

- src/main/resources/lib/office-pages/_legacy-office-information/legacy-office-update.ts
- src/main/resources/lib/office-pages/office-tasks.ts
- src/main/resources/main.ts
Importjobbene for kontor-import hadde stoppet. Jeg sletter schedule-nodene og deployer på nytt, men benytter samtidig anledningen til bedre jobb-navn slik at det er lettere å skille mellom hva som er "ny" kontorimport og hva som er legacy (som vi kanskje snart kan droppe...
Testet i q6
> Forbedrer navning og cronjobb for office-importering

- src/main/resources/lib/archiving/batch-archiving.ts
- src/main/resources/main.ts
- Reaktiverer schedule for arkivering av pressemeldinger, nyheter og aktuelt-sider hver mandags morgen.
- Setter inn unntak for aktuelt-sider: Kun aktueltsider som ikke har noen planlagt avpublisering (dvs som bare blir liggende i evig tid) skal arkiveres når from er mer en 1 år bakover i tid. Utover det skal de få ligge.
- Fjerner utkommentert kode om sjekk av referanser. Det er ikke ønskelig å ta denne funksjonen inn igjen i det heletatt.
Testes i dev med utvalgte artikler. Sjekkes mandags morgen at alt er OK
> Aktivere mandagsarkivering. Unntak for aktuelt-artikler med planlag avpublisering
