navikt/nav-enonicxp

src/main/resources/site/assets/js/google-tag-manager.js, src/main/resources/site/pages/main-page/main-page.js
Endringer kan komme ifm. ny dekoratør
=> Lagt til GTM js-fil og script-tag

src/main/resources/site/macros/button/button.js, src/main/resources/site/macros/button/button.xml, src/main/resources/site/macros/quote/quote.js, src/main/resources/site/macros/quote/quote.xml
Lagt til to makroer - blå knapp og sitat. Avklart med Janne i komm.staben.
=> Lagt til to makroer. Legg til blå knapp og legg til sitat. (IV-570)

src/main/resources/lib/guillotine/queries/run-content-query.ts, src/main/resources/lib/guillotine/schema/schema-creation-callbacks/richtext.ts, src/main/resources/lib/guillotine/utils/content-query-context.ts, src/main/resources/lib/localization/layers-migration/migrate-content-to-layer.ts, src/main/resources/lib/localization/layers-migration/modify-content-node.ts, src/main/resources/lib/localization/layers-migration/update-content-references.ts, src/main/resources/lib/localization/locale-context.ts, src/main/resources/services/sitecontent/generate-response.ts
...og diverse layers-relaterte endringer
=> Fikser url-resolving for lenker til ikke-norsk innhold i default-layeret

src/main/resources/admin/widgets/migrate-to-layer/migrate-to-layer.html, src/main/resources/admin/widgets/migrate-to-layer/migrate-to-layer.ts
Kan nå søke og velge innhold fra en dropdown, istedenfor å måtte skrive inn en content id
=> Skriver om migreringswidget til å bli mer brukervennlig

src/main/resources/services/officeInfo/officeInfo.ts
Fikser manglende stripPathPrefix for tjenesten officeInfo som leverer liste av kontorer og korrekte stier
=> Fikser manglende stripPathPrefix for officeInfo

src/main/resources/lib/controllers/form-intermediate-step-controller.ts, src/main/resources/lib/paths/custom-paths/custom-path-special-types.ts, src/main/resources/lib/paths/custom-paths/custom-path-utils.ts, src/main/resources/services/customPathSelector/customPathSelector.ts, src/main/resources/site/content-types/form-intermediate-step/form-intermediate-step.ts, src/main/resources/site/content-types/form-intermediate-step/form-intermediate-step.xml, src/main/resources/site/site.xml
Usikkert om dette er den faktiske url-strukturen vi skal ha, men funksjonaliteten skal være klar.
=> Setter customPath programmatisk på mellomsteg

src/main/resources/services/selectedFormDetails/selectedFormDetails.ts, src/main/resources/site/content-types/guide-page/guide-page.ts, src/main/resources/site/content-types/guide-page/guide-page.xml, src/main/resources/site/parts/form-details/form-details.xml
Legger til skjemadetaljer for "Slik gjør du det"-siden.
=> Legger til mulighet for at guide-page også kan ha skjemadetaljer

src/main/resources/lib/guillotine/queries/fragments/content-types/formsOverviewFragment.graphql, src/main/resources/lib/guillotine/schema/schema-creation-callbacks/forms-overview-data-callback.ts
- Håndterer manglende data.title felt
- Legger til anchorId felt
=> Fixes for skjemaoversikt

src/main/resources/lib/guillotine/schema/schema-creation-callbacks/forms-overview-data-callback.ts, src/main/resources/site/content-types/forms-overview/forms-overview.ts, src/main/resources/site/content-types/forms-overview/forms-overview.xml, src/main/resources/site/mixins/taxonomy/taxonomy.xml
- Legger til valg av oversiktstype, og henter kun relevante skjemadetaljer for valgt type
- Legger til valg av undersider for samarbeidspartner landingssider
- Legger til toggle for samtlige filter-typer
=> Forms overview continued

src/main/resources/lib/guillotine/queries/fragments/content-types/formsOverviewFragment.graphql, src/main/resources/site/content-types/forms-overview/forms-overview.ts, src/main/resources/site/content-types/forms-overview/forms-overview.xml
- Legger til felt for lenketekst på lenker til samarbeidspartner undersider
- Legger til manglende felter i queryet
=> Skjemaoversikt fixes

src/main/resources/lib/localization/layers-migration/migrate-content-to-layer.ts, src/main/resources/services/migrateToLayers/migrateToLayers.ts, src/main/resources/site/content-types/forms-overview/forms-overview.ts
- Bruker post-endepunkt for preset batch migrering, for mulighet for større payloads
- Pauser cache-invaliderings eventer ved migrering
=> Tweaker layer-migrerings service

src/main/resources/lib/guillotine/schema/schema-creation-callbacks/forms-overview-data-callback.ts, src/main/resources/lib/paths/custom-paths/custom-path-special-types.ts, src/main/resources/site/content-types/current-topic-page/current-topic-page.ts, src/main/resources/site/content-types/forms-overview/forms-overview.ts, src/main/resources/site/content-types/guide-page/guide-page.ts, src/main/resources/site/content-types/situation-page/situation-page.ts, src/main/resources/site/content-types/tools-page/tools-page.ts, src/main/resources/site/mixins/area/area.ts, src/main/resources/site/mixins/product-data/product-data.ts, src/main/resources/site/mixins/provider-audience/provider-audience.ts, src/main/resources/site/mixins/provider-audience/provider-audience.xml, src/main/resources/site/mixins/taxonomy/taxonomy.ts, src/main/resources/site/mixins/themed-article-data/themed-article-data.ts
...og fikser audience-håndtering for mellom-steg url'er
=> Tillater flere underkategorier for samarbeidspartner

src/main/resources/services/migrateToLayers/migrateToLayers.ts
Oppdaterer status underveis i en migreringsbatch
=> Bedre status-response for preset migrering

src/main/resources/lib/guillotine/queries/fragments/components/parts/partFormDetails.graphql, src/main/resources/site/parts/form-details/form-details-part-config.ts, src/main/resources/site/parts/form-details/form-details.xml
Legger til mulighet for filter i part for skjemadetalj
Testes i Q6.
=> Legger til filter for skjemadetaljer-part

src/main/resources/lib/contentUpdate/contentUpdateListener.ts
Sjekker om videocover finnes før det evt slettes og så opprettes på nytt.
Testet i Q6
=> Sjekk og slett eksisterende videoposter før opprettelse av ny

.nais-deploy-job/deploy-job.yml
Fikser feil i host på accessPolicy.external
=> Fikser feil i host i accessPolicy

src/main/resources/lib/constants.ts, src/main/resources/lib/controllers/component-preview-controller.ts, src/main/resources/lib/controllers/frontend-proxy.ts
Se https://github.com/navikt/nav-enonicxp-frontend/pull/1442
=> Endrer til nye frontend dev-urler

src/main/resources/lib/contentUpdate/content-update-listener.ts, src/main/resources/lib/fragmentCreator/fragment-creator.ts, src/main/resources/site/content-types/fragment-creator/fragment-creator.xml
- Setter part som default-type
- Kjører content-update-listener i riktig repo context
=> Tweaker fragment-creator

src/main/resources/lib/guillotine/queries/fragments/components/parts/partFrontpageShortcuts.graphql, src/main/resources/lib/guillotine/queries/fragments/mixins/legacyShortFragments.graphql, src/main/resources/site/content-types/forms-overview/forms-overview.ts, src/main/resources/site/content-types/forms-overview/forms-overview.xml, src/main/resources/site/parts/frontpage-shortcuts/frontpage-shortcuts-part-config.ts, src/main/resources/site/parts/frontpage-shortcuts/frontpage-shortcuts.xml
- Tar med title-felt for nye sidetyper til legacy lenkepaneler
- Legger til fargevelger på frontpage-shortcuts
- Legger til externalProductUrl på skjemaoversikt
=> Titles for nye sidetyper til legacy lenkepaneler ++

src/main/resources/site/parts/filters-menu/filters-menu-part-config.ts, src/main/resources/site/parts/filters-menu/filters-menu.xml
Gjort etter dialog med Tuva og Janne.
Testet selv lokalt og i dev
=> Gjør kategorinavn for filtermeny obligatorisk + endrer tekster

src/main/resources/lib/guillotine/queries/fragments/components/pagesFragment.graphql, src/main/resources/services/sitecontentArchive/sitecontentArchive.ts
Hovedsakelig relatert til sider som bruker page templates
=> Fikser diverse issues med visning av innhold i arkivet

src/main/resources/lib/cache/find-references.ts, src/main/resources/lib/guillotine/queries/fragments/content-types/formsOverviewFragment.graphql, src/main/resources/lib/guillotine/schema/schema-creation-callbacks/forms-overview-data-callback.ts, src/main/resources/site/content-types/form-details/form-details.ts, src/main/resources/site/content-types/form-details/form-details.xml
- Invaliderer cache for skjemaoversikter når skjemadetaljer publiseres
- Setter title på skjemadetaljer til påkrevd
- Inkluderer ingress-tekst for skjemadetaljer i skjemaoversikter
=> Diverse skjemaoversikt justeringer

src/main/resources/lib/search/create-or-update-search-node.ts, src/main/resources/site/content-types/form-details/form-details.ts, src/main/resources/site/content-types/form-details/form-details.xml
Genererer href til skjema ved indeksering av skjemadetaljer
=> Tilpasser søke-indeksering for skjemadetaljer

src/main/resources/site/content-types/form-details/form-details.ts, src/main/resources/site/content-types/form-details/form-details.xml
Begge deler er tiltenkt bruk i søket
=> Legger til audience og "longTitle" på skjemadetaljer

src/main/resources/services/video/video.ts, src/main/resources/services/video/video.xml
- Oppretter en tjeneste for å sjekke innhold hvor en bestemt video-content er brukt via macro.
Testet i dev
=> Service for sjekk av innhold hvor video-makro er brukt

src/main/resources/lib/contenttype-lists.ts, src/main/resources/lib/guillotine/queries/content-queries/calculatorQuery.graphql, src/main/resources/lib/guillotine/queries/run-content-query.ts
Legger til manglende content type query for calculator
Testes i dev
=> Legger til contenttype query for calculator

src/main/resources/site/content-types/video/video.ts, src/main/resources/site/content-types/video/video.xml
Tydeliggjøre i tekst at video-innholdstypen gjelder for Qbrick-videoer.
Testes i q6
=> Presiserer av det er Qbrick-videoer som må brukes

.github/workflows/build-deploy-image.yml, .github/workflows/deploy-to-dev.yml, .github/workflows/deploy-to-prod.yml, .github/workflows/deploy-to-q6.yml
Bytter docker build action til nais/docker-build-push, som benytter Google Artifact Registry
=> GHCR -> GAR

src/main/resources/lib/localization/layers-migration/migrate-content-to-layer.ts, src/main/resources/lib/localization/layers-migration/migration-data.ts, src/main/resources/lib/time-travel/get-content-from-datetime.ts, src/main/resources/lib/utils/version-utils.ts, src/main/resources/main.ts, src/main/resources/services/sitecontentArchive/sitecontentArchive.ts, src/main/resources/services/sitecontentVersions/publishedVersions/publishedVersions.ts, src/main/resources/services/sitecontentVersions/sitecontentVersions.ts
Tiltenkt innhold som har blitt migrert fra root-prosjektet til språk-layers
=> Følger referanser til annet innhold ved uthenting av versjonshistorikk

src/main/resources/main.ts
Hindrer overbelastning pga veldig stort antall events ved oppsett av layers
=> Slår av event listeners

src/main/resources/lib/controllers/component-preview-controller.ts, src/main/resources/lib/localization/layers-migration/update-content-references.ts, src/main/resources/lib/time-travel/time-travel-hooks.ts, src/main/resources/main.ts, src/main/resources/services/productDetailsSelector/productDetailsSelector.ts
Fikser previews av komponenter og produktdetaljer fra selector
=> Diverse layers-relaterte fixes

src/main/resources/site/content-types/front-page-nested/front-page-nested.ts, src/main/resources/site/content-types/front-page-nested/front-page-nested.xml
Tillater videresending av underforside til annen URL.
Testet i Q6
=> Legger til støtte for å kunne videresende underforside

src/main/resources/lib/paths/custom-paths/custom-path-utils.ts, src/main/resources/services/customPathSelector/customPathSelector.ts
Justerer Regexp til å ikke godta trailling slash
Har selv testet lokalt og i dev
=> Kort-urler kan ikke slutte med /

src/main/resources/site/mixins/provider-audience/provider-audience.xml
Endret tekst i underkategori til Samarbeidspartner
Har testet selv lokalt og i dev
=> Endret tekst i en underkategori paa  Samarbeidspartner

src/main/resources/lib/guillotine/schema/schema-creation-callbacks.ts, src/main/resources/lib/guillotine/schema/schema-creation-callbacks/content-list-callback.ts, src/main/resources/site/parts/frontpage-current-topics/frontpage-current-topics-part-config.ts, src/main/resources/site/parts/frontpage-current-topics/frontpage-current-topics.xml
Redaktørene kan slå på sortering i selve parten som deretter blir fanget opp av partens callback.
Testes i Q6.
=> Sorterer nyheter korrekt på Seksjon for aktuelle temaer

config/dev/com.enonic.xp.content.cfg, config/localhost/com.enonic.xp.content.cfg, config/p/com.enonic.xp.content.cfg, config/q6/com.enonic.xp.content.cfg
Lagt til resolveEmptyRegions=true
=> Lagt til resolveEmptyRegions i cfg

src/main/resources/lib/sitemap/sitemap.ts
Ser ut til å kun skje i prod, ikke dev eller lokalt 🤔
=> Logging for å debugge hvorfor sitemap-service'en i prod returnerer færre entries enn forventet

src/main/resources/lib/forms-overview/form-details-list-builder.ts, src/main/resources/lib/guillotine/queries/fragments/content-types/overviewFragment.graphql, src/main/resources/lib/guillotine/schema/schema-creation-callbacks/overview-data-callback.ts, src/main/resources/lib/product-utils/productList.ts, src/main/resources/lib/product-utils/types.ts, src/main/resources/lib/utils/sort-utils.ts
Skriver om callback-funksjoner som genererer liste til overviews slik at hver item kan lenke til flere sider
=> Støtter lenker til flere produktsider fra en produktdetalj på oversikter

src/main/resources/lib/contentUpdate/video-update.ts
Noen gamle videoer ser ut til ikke å ha noen duration verdi...
=> Setter qbrick metadata selv om duration er 0

src/main/resources/lib/reference-search/references-finder.ts, src/main/resources/site/content-types/forms-overview/forms-overview.xml
- Sørger for at produktdetaljer finner relevante oversiktssider som referanser
- Fikser bug med en customselector for skjemaoversikt
- Sørger for at referansesøk for et innhold ikke finner seg selv som referanse
=> Diverse bugfixes for oversiktssider

babel-logger-transformer.js, src/main/resources/lib/reference-search/references-finder.ts, src/main/resources/lib/search/external/document-builder/document-builder.ts, src/main/resources/lib/search/external/document-builder/field-resolvers/audience.ts, src/main/resources/lib/search/external/document-builder/field-resolvers/content-type.ts, src/main/resources/lib/search/external/document-builder/field-resolvers/metatags.ts, src/main/resources/lib/search/external/document-builder/field-resolvers/text.ts, src/main/resources/lib/utils/logging.ts, src/main/resources/site/parts/user-tests/user-tests-part-config.ts, src/main/resources/types/content-types/content-config.d.ts
Fikser også en bug med logging av filnavn/linjenummer dersom loglevel settes runtime
=> Type-felt for eksternt søk + logger bugfix

src/main/resources/site/content-types/user-tests-config/user-tests-config.ts, src/main/resources/site/content-types/user-tests-config/user-tests-config.xml
=> Endrer type for prosentandel av brukertest-varianter fra Long til Double

src/main/resources/lib/cache/invalidate-event-handlers.ts, src/main/resources/lib/cache/invalidate-specal-content-types.ts, src/main/resources/lib/guillotine/queries/fragments/components/parts/partFrontpageContact.graphql, src/main/resources/lib/guillotine/schema/schema-creation-callbacks/common/opening-hours-mixin.ts, src/main/resources/lib/scheduling/scheduled-publish.ts, src/main/resources/site/mixins/opening-hours/opening-hours.xml, src/main/resources/site/parts/frontpage-contact/frontpage-contact-part-config.ts, src/main/resources/site/parts/frontpage-contact/frontpage-contact.xml
Legger inn mulighet for å referere spesielle åpningstider på komponenten på forside.
Merges inn i relatert branch før videre testing.
=> Spesielle apningstider forside

src/main/resources/lib/guillotine/queries/fragments/components/parts/partFrontpageShortcuts.graphql, src/main/resources/site/parts/frontpage-shortcuts/frontpage-shortcuts.xml
Det er behov for å kunne lenke til artikkellister (page-list) i snarveier på forsider / underforsider.
Testes i dev.
=> Tillate artikkelliste i seksjon for snarveier

src/main/resources/lib/search/external/document-builder/document-builder.ts, src/main/resources/lib/search/external/document-builder/field-resolvers/fylke.ts, src/main/resources/lib/search/external/document-builder/field-resolvers/language.ts, src/main/resources/lib/search/external/document-builder/field-resolvers/metatags.ts, src/main/resources/lib/search/external/document-builder/field-resolvers/text.ts, src/main/resources/types/components/component-node.d.ts
Se issues for hva som er fikset :)
=> Diverse tweaks for indeksering til eksternt søk

README.md, config/com.enonic.app.contentstudio.cfg
- Oppdaterer Readme til å inkludere alle nye config-filer som trengs
- (en del automatiske formateringsendringer i Readme)
Er det riktig? Gir det mening å legge `com.enonic.app.contentstudio.cfg` direkte i config-mappa?
=> Oppdater Readme med nye config-filer

src/main/resources/lib/guillotine/queries/fragments/content-types/overviewFragment.graphql, src/main/resources/lib/guillotine/schema/schema-creation-callbacks/overview-data-callback.ts, src/main/resources/lib/product-utils/productList.ts, src/main/resources/lib/product-utils/types.ts
...slik at disse kan bli søkbare i frontend
=> Inkluderer keywords i data for oversiktssider

src/main/resources/site/content-types/guide-page/guide-page.xml
Presisering: Endret tekst på displayName, ikke selve malen.
Har testet lokalt og q6
=> Endret displayName fra Guide ("Slik gjør du") til Slik gjør du det

src/main/resources/lib/scheduling/scheduled-publish-updater.ts, src/main/resources/lib/scheduling/scheduled-publish.ts
Ble fjernet ved et uhell før jul 😅
=> Gjeninnfører scheduled unpublish for expired content

src/main/resources/lib/guillotine/queries/fragments/components/parts/partFrontpageCurrentTopics.graphql, src/main/resources/site/parts/frontpage-current-topics/frontpage-current-topics-part-config.ts, src/main/resources/site/parts/frontpage-current-topics/frontpage-current-topics.xml
Legger til funksjon for lenke (intern eller ekstern) fra aktuelt-seksjonen på forside.
Testes i dev
=> Legger til lenke til seksjon for artikler på forside

src/main/resources/site/mixins/alternative-audience/alternative-audience.xml
=> Fikser skrivefeil i felt for andre samarbeidspartnere

src/main/resources/lib/office-pages/office-update.ts
For kontorsider hvor redaktørene endrer kontorsider direkte må importen sjekke om siden faktisk bør publiseres. Dersom den ikke er i sync med master, blir norg-data oppdatert, men siden blir ikke publisert. Da må det i såfall gjøres manuelt.
Testes i q6
=> Legger på sjekk på om et kontor kan publiseres

src/main/resources/lib/time-travel/get-content-from-datetime.ts, src/main/resources/lib/time-travel/run-with-time-travel.ts, src/main/resources/services/sitecontentVersions/sitecontentVersions.ts
Setter riktig repo-context ved uthenting av versjonshistorikk
=> Fikser visning av versjonshistorikk i layers

.eslintrc.cjs, src/main/resources/lib/cache/draft-cache.ts, src/main/resources/lib/cache/invalidate-event-handlers.ts, src/main/resources/lib/constants.ts, src/main/resources/services/sitecontent/draft/draft-response.ts
Sletter hele draft-cachen hver gang et content oppdateres
=> Invaliderer draft-cache

.xp-codegen/site/parts/accordion/index.d.ts, src/main/resources/lib/guillotine/queries/fragments/components/parts/partAccordion.graphql, src/main/resources/site/parts/accordion/accordion.xml
Legger til støtte for ankerId i trekkspill.
Testes i dev
=> Legger til støtte for ankerId i trekkspill

src/main/resources/lib/controllers/frontend-proxy.ts
… og erstatter dette med valgfri nedlastingslenke
=> Fikser bug som førte til at filer uten forhåndsvisning automatisk ble lastet ned

src/main/resources/site/mixins/seo/seo.xml
- Oppdaterer help-text for nosnippet i forbindelse med https://github.com/navikt/nav-enonicxp-frontend/pull/1797
Har testet selv lokalt
Gir teksten mening?
=> Endre help-text nosnippet

src/main/resources/lib/contentUpdate/video-update.ts, src/main/resources/lib/controllers/frontend-proxy.ts, src/main/resources/services/customPathSelector/customPathSelector.ts
Litt forsinkelser lokalt - Eivind har verifisert at det samme skjer hos han. Skyldes kanskje oppdatering av HttpClient? Foreslår å øke timeout noe.
=> Øker diverse timeout for henting via httpClient

src/main/resources/lib/office-pages/_legacy-office-information/legacy-office-update.ts, src/main/resources/lib/office-pages/office-update.ts
Fjerner importering av kontortype KLAGE. Importeres kun ved legacy kontor-import.
Testes i dev
=> Fjerner importering av kontortype KLAGE

.xp-codegen/site/parts/html-area/index.d.ts, src/main/resources/site/mixins/ingress-required/ingress-required.xml, src/main/resources/site/parts/html-area/html-area.xml
- Angir innholdstype i html-area
- Legger til begrensninger i lengde på ingress
=> Angi innholdstype for expandable

.xp-codegen/site/pages/page-with-side-menus/index.d.ts, src/main/resources/site/pages/page-with-side-menus/page-with-side-menus.xml
Støtter 'dette' istedet for å vise produktnavn i aktuelle situasjoner
=> Støtter 'dette' istedet for å vise produktnavn i aktuelle situasjoner

src/main/resources/lib/contenttype-lists.ts
Fjerner brødsmulesti på utvalgte innholdstyper. Diskuteres fortsatt, så det er mulig dette blir reversert. Kjapt gjort i såfall.
=> Fjerner brødsmulestier fra enkelte innhold

src/main/resources/site/parts/alternative-audience/alternative-audience.xml
Retter skrivefeil i beskrivelse av part for aktuelle målgrupper
=> Retter skrivefeil i beskrivelse av part for aktuelle målgrupper

.xp-codegen/site/parts/html-area/index.d.ts, src/main/resources/site/parts/html-area/html-area.xml
Legger til flere typer innhold for ekspanderbart panel
Testes i dev
=> Legger til flere typer innhold for ekspanderbart panel

src/main/resources/services/sitecontent/public/special-redirects.ts
Sjekker at siden som skal redirectes faktisk er en lokalkontorside. Andre kontorsider slik som feks hjelpemiddelsentral avpubliseres manuelt.
Testes i dev
=> Fikser feil redirect fra hjelpemiddelsider

src/main/resources/lib/office-pages/_legacy-office-information/legacy-office-update.ts
Stopper import av HMS og LOKAL.
=> Stopper import av Hjelpemiddelsentral og Lokalkontor for legacy kontorsider

src/main/resources/lib/search/event-handlers.ts
Laster ny config for søket på alle noder, ikke kun main data node
=> Revaliderer search config på alle noder

src/main/resources/lib/office-pages/_legacy-office-information/legacy-office-update.ts
Legger til NAV Registerforvaltning + refactor
=> Whitelist for individuelle enheter i legacy office import

src/main/resources/admin/widgets/dashboard-content/dashboard-content.ts, src/main/resources/admin/widgets/dashboard-content/utils/contentResolver.ts
- Viser språklayer som engelsk/nynorsk/samisk i stedet for en, nn og se 
Har testet selv i dev
=> Navn på layer som klartekst (engelsk/nynorsk/samisk) 

src/main/resources/admin/widgets/dashboard-content/dashboard-content.xml, src/main/resources/admin/widgets/dashboard/dashboard.xml
Endret rekkefølge på redaktør-melding og oversikt over innhold
Har testet selv i dev / lokalt
=> Endret rekkefølge på redaktør-widgets

src/main/resources/lib/guillotine/schema/schema-creation-callbacks/richtext.ts
Fikser bugs som kan oppstå dersom anchor-elementet har uventede attributes. F.eks. fungerer ikke resolveren på denne med dagens løsning:
`<a href="/some/url" style="color: red" data-link-ref="1234><!--osv"`
=> Forbedrer resolver for public paths i richtext

src/main/resources/lib/paths/path-utils.ts, src/main/resources/services/contentTree/contentTree.ts
Ny service for ny versjonshistorikk
=> Content tree service

src/main/resources/lib/paths/path-utils.ts, src/main/resources/services/externalArchive/contentTree/contentTree.ts
Støtter layers i contentTree service
=> Content tree layers

src/main/resources/admin/widgets/dashboard-content/dashboard-content.ts, src/main/resources/admin/widgets/dashboard-content/utils/types.ts
Endrer testing på om innhold er endret etter en eventuell avpublisering.
Testet i q6
=> Widget fix date test

src/main/resources/lib/office-pages/_legacy-office-information/legacy-office-update.ts
Stopper import av HMS for Trøndelag.
Testes i dev
=> Stopper HMS-import for HMS Trøndelag

src/main/resources/lib/office-pages/_legacy-office-information/legacy-office-update.ts
Stopper import av HMS Bergen og Førde
=> Stopper import av HMS Bergen og Førde

src/main/resources/lib/utils/string-utils.ts
Justerer grådighet slik at scriptet søker på "NAV Hjelpemiddelsentral" og ikke bare "Hjelpemiddelsentral".
=> Justerer ned grådighet for erstatningssøk ved NAV=>Nav

src/main/resources/lib/utils/string-utils.ts
Fikser feil i erstatningslenke for søknader
=> Fikser feil i erstatningslenke for søknader

src/main/resources/lib/utils/string-utils.ts
Legger til url-relaterte felter som unntak.
=> Legger til 'url' som unntak for erstatning

src/main/resources/lib/utils/string-utils.ts
Hopper over tekst som inneholder "attachment" i denne omgang. Må finne en bedre måte å håndtere redaktør-url.
Testet i dev
=> Hopper over tekst som inneholder 'attachment'

src/main/resources/lib/utils/string-utils.ts
Forbedrer sjekk av tekststreng som inneholder anker-element slik at NAV => Nav ikke erstattes i feks url. Samtidig skal all tekst rundt erstattes.
Testet i dev
=> Forbedrer utelukkelse av URL.

src/main/resources/admin/widgets/dashboard-content/dashboard-content.ts, src/main/resources/admin/widgets/dashboard-content/utils/contentResolver.ts
Økt antall queries fra 5 til 50.
Splicer resultatet for å vise de 5 siste elementene.
Har testet selv i dev / lokalt
=> Øker query fra 5 til 50, men må splice til 5 visninger

src/main/resources/lib/scheduling/schedule-job.ts, src/main/resources/lib/scheduling/scheduled-publish.ts
Legger til forbedret feillogging ved feilet scheduling.
Testes i dev
=> Legger til forbedret feillogging ved feilet scheduling

src/main/resources/lib/scheduling/schedule-job.ts, src/main/resources/lib/scheduling/scheduled-publish.ts
Legger på logging for prepublish
=> Legger på logging for prepublish

src/main/resources/lib/scheduling/schedule-job.ts, src/main/resources/lib/scheduling/scheduled-publish.ts
Legger på mer logging for å feilsøke manglende scheduling i prod.
=> Legger på logging for planlagt publisering

src/main/resources/lib/cache/invalidate-event-handlers.ts
Legger på logging for invalidate-event-handlers
Testet i dev
=> Legger på logging for invalidate-event-handlers

src/main/resources/site/content-types/content-list/content-list.xml
Lagt til contentType office-page i Innholdsliste
Har testet selv i q6 og lokalt
=> Mulighet for å legge til kontorsider i Innholdslister

src/main/resources/site/content-types/content-list/content-list.xml
Lagt til muligheten for å legge til generisk side i innholdslister
Har testet selv i dev
=> Lagt til generic-page i innholdslister

src/main/resources/lib/search/document-builder/field-resolvers/text.ts, src/main/resources/lib/search/event-handlers.ts, src/main/resources/lib/search/update-references.ts
Sjekker referanser til innhold og oppdaterer søkeindeks deretter.
Resolver fragmenter som er satt inn som macroer.
Testes i dev
=> Sjekker referanser og oppdaterer søkeindeks

src/main/resources/services/externalArchive/search/search.ts
Søker kun i utvalgte sidetyper. Gjør at søket er mye raskere
=> Søk kun i utvalgte sidetyper i eksternt arkiv

src/main/resources/services/externalArchive/search/search.ts
https://github.com/navikt/navno-cms-archive/pull/69
=> add content type filtering to archive search

.xp-codegen/site/layouts/product-flex-cols/index.d.ts, .xp-codegen/site/mixins/header-with-anchor/index.d.ts, src/main/resources/admin/widgets/dashboard-content/dashboard-content.html
=> Overskrift dashboard widget

.xp-codegen/site/layouts/product-flex-cols/index.d.ts, .xp-codegen/site/mixins/header-with-anchor/index.d.ts, src/main/resources/services/dataQuery/utils/queryBuilder.ts
-   Merget de to must-filter variantene.
Eks: Har testet selv i dev / q6
=> Skyggesider

.xp-codegen/site/parts/frontpage-current-topics/index.d.ts, .xp-codegen/site/parts/frontpage-shortcuts/index.d.ts, src/main/resources/lib/guillotine/queries/fragments/components/parts/partFrontpageCurrentTopics.graphql, src/main/resources/site/parts/frontpage-contact/frontpage-contact.xml, src/main/resources/site/parts/frontpage-current-topics/frontpage-current-topics.xml, src/main/resources/site/parts/frontpage-shortcuts/frontpage-shortcuts.xml
La også til mulighet for å overstyre bakgrunns- og elementfarge på aktuelt-komponent
=> Endring av farger for aktuelt og kontakt oss

.github/workflows/deploy-to-prod.yml, .github/workflows/pr-tests.yml, .prettierignore
- Oppdaterer workflows til 'main'
- Legger inn yml og yaml i prettierignore.
Ikke mulig å teste i dev siden endringene sjekker at commit ligger i main før den kan deployes.
=> Oppdaterer workflows til å sjekke mot 'main'

src/main/resources/lib/external-archive/content-tree-archive.ts, src/main/resources/lib/external-archive/content-tree.ts
Filtrerer ut ikke-lokalisert innhold i layers
Fjerner migrert innhold
=> Localized content

src/main/resources/services/externalArchive/content/content.ts
legger til orignal innholdstype på xp-innhold som er interne eller eksterne lenker _om_ de hadde en annen innholdstype før
=> legg til original innholdstype

.github/workflows/deploy-to-prod.yml
Branch name skal være navn på release
=> Automatic release

src/main/resources/lib/utils/content-utils.ts, src/main/resources/services/dataQuery/utils/queryBuilder.ts, src/main/resources/services/dataQuery/utils/queryRunners.ts, src/main/resources/services/dataQuery/utils/types.ts, src/main/resources/services/externalArchive/search/search.ts
-   Endret previewfilter til å fjerne både de som ikke har satt previewOnly _og_ de som har det satt til false.
-  Lager egen spørring for eksternt arkiv med filtrene denne trenger for å isolere fra resten
- Kun returnere unike treff, da vi må søke i både draft og master
Har testet selv i dev
=> Improved preview filter and only unique hits

.xp-codegen/site/content-types/contact-information/index.d.ts, src/main/resources/lib/guillotine/queries/fragments/components/parts/partContactOption.graphql, src/main/resources/lib/guillotine/queries/fragments/content-types/contactInformationFragment.graphql, src/main/resources/site/content-types/contact-information/contact-information.xml
Det må være mulig å ikke referere til "Flere telefonnummer og tastevalg", så legger inn sjekkboks for dette slik at redaktørene kan styre det selv.
Testes i dev
=> Legger til sjekkboks for å skjule info om flere telefonnr

src/main/resources/webapp/webapp.ts
Klargjør for testing av arkiveringsfunksjon. Påvirker kun visning i webapp i dev og i localhost.
Testes i dev
=> Åpner for arkivering i dev og localhost

.xp-codegen/site/content-types/contact-step-page/index.d.ts, src/main/resources/lib/guillotine/queries/fragments/content-types/contactStepPageFragment.graphql, src/main/resources/site/content-types/contact-step-page/contact-step-page.xml
Bruk link-internal mixin på lenkepaneler og tilbakelenke
=> Contact step page external links

src/main/resources/services/dataQuery/utils/queryBuilder.ts, src/main/resources/services/dataQuery/utils/queryRunners.ts
-   Søker som admin for å få med alle treff
-  Tydligere filter på previewOnly-verdien
Eks: Har testet selv i dev
=> Improve search to find articles in other layers

src/main/resources/services/dataQuery/utils/queryBuilder.ts
-  Fjernet treff som er migrert fra søket til eksternt arkiv
Eks: Har testet selv i dev
=> remove  migrated to layer from external search

src/main/resources/services/dataQuery/utils/queryBuilder.ts, src/main/resources/services/externalArchive/search/search.ts
-  Lagt til språk i søketreff for arkiv
- Fjerne locale-filter i søk 
Har testet selv i dev
=> Add language and remove locale filter

src/main/resources/main.ts
=> Reaktivere event listeners

src/main/resources/lib/archiving/batch-archiving.ts
Legger innhold som ble hoppet over ved arkiveringsrunde i egen bøtte slik at det tydeliggjøres mer.
Testet i dev
=> Fikser logikk for avpubliserings rutine

src/main/resources/main.ts
Har kjørt et par uker i dev. Dette åpner opp i prod.
Janne har også testet i dev og funnet i orden.
=> Åpner for arkiveringsschedule hver mandags morgen

src/main/resources/site/macros/uxsignals-widget/uxsignals-widget.xml, src/main/resources/site/parts/uxsignals-widget/uxsignals-widget.xml
Kjapp fiks for å legge til hjelpetekst for felt i UXSignals-widget
Testes i Q6 for ordens skyld
=> Legger inn en hjelpetekst for UXSignals

src/main/resources/main.ts
Stopper schedule for mandagsarkivering midlertidig.,
=> Stopper mandagsarkivering midlertidig

src/main/resources/lib/external-archive/get-content.ts, src/main/resources/lib/time-travel/get-published-versions.ts, src/main/resources/lib/utils/content-utils.ts, src/main/resources/services/externalArchive/content/content.ts
- Sjekker at en version faktisk har en publish.from dato
Har testet selv i q6
=> Latest version bug

.xp-codegen/site/content-types/oversikt/index.d.ts, src/main/resources/lib/overview-pages/oversikt-v3/form-details-utils.ts, src/main/resources/lib/overview-pages/oversikt-v3/helpers.ts, src/main/resources/lib/overview-pages/oversikt-v3/transform-to-oversikt-item.ts, src/main/resources/site/content-types/oversikt/oversikt.xml
- Velge flere målgrupper og undermålgrupper for en oversiktsside
- Justerer filterlogikk
Testes i dev
=> Velge flere malgrupper oversiktssider

src/main/resources/site/content-types/oversikt/oversikt.xml
Legger til "Forvaltes av" for oversiktssider.
Testes i dev
=> Legger til managed-by i oversiktsside

src/main/resources/lib/guillotine/queries/fragments/components/parts/partFrontpagePersonShortcuts.graphql, src/main/resources/lib/guillotine/queries/fragments/components/parts/partFrontpageShortcuts.graphql, src/main/resources/lib/guillotine/queries/fragments/mixins/frontPageNavigationReferences.graphql, src/main/resources/lib/guillotine/queries/fragments/mixins/productTargetFragment.graphql, src/main/resources/lib/search/document-builder/field-resolvers/content-type.ts
- Åpner for at oversikter også sendes for indeksering til søk.
- Fikser queries for visning av snarveier
Testes i dev
=> Oversikt i sok og korrigerer queries
